### ISSUE TITLE
Ping failed

### ISSUE THREAD

**Issue by sonht1109** [dante4rt/nodepay-airdrop-bot#21]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/ee3dd634-57fc-4d2e-b87a-c4b984a0ce1b">

seems bot is not working now

**Comment by Lukey372** [comment]
Most recent push fixed it

**Comment by sonht1109** [comment]
thank guyss

**Comment by Airdroprozana** [comment]
> Most recent push fixed it

Bro Its Still Working Our Not?? Its Show Ping Error On My This Time
